### ISSUE TITLE
HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by 3even** [vexxxed/soundcloud-page-downloader#7]
Received the following error when trying to download files from a page:

Traceback (most recent call last):
  File "soundcloud-downloader.py", line 127, in <module>
    main(parsed_args)
  File "soundcloud-downloader.py", line 109, in main
    track['user']['permalink'], track_title, track_genre)
  File "soundcloud-downloader.py", line 47, in download_file
    u = urllib2.urlopen(download_url)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized

**Comment by neonobjclash** [comment]
Everything should work in [my fork](https://github.com/neonobjclash/soundcloud-page-downloader)

**Comment by vexxxed** [comment]
This repo was fucked up ages ago by some cunt who decided to rewrite it and mess up the readability beyond compare. Don't expect it to work anymore. I'll rewrite it in the coming weeks.

**Comment by 3even** [comment]
For anyone still interested. I've been simply using the [SoundCloud API](https://developers.soundcloud.com/docs/api/reference) to grab tracks off a user's profile then pull each one down using [youtube-dl](https://rg3.github.io/youtube-dl/)

**Comment by vexxxed** [comment]
Stop that. Stop that. Go the fuck away.
